issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - gosimple
    - ineffassign
    - misspell
    # Run separately for TravisCI memory issues
    # - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
    - vet

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/:ForceNew,Set,fmt:.*,io:Close

run:
  deadline: 5m
