dist: xenial
sudo: required
services:
  - docker
language: go

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - go: "1.13.x"
      name: "Lint"
      script: make lint
    - go: "1.13.x"
      name: "UnitTest"
      script: make test

install:
  - make tools
